# Generated by Django 4.2.4 on 2023-08-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sederek', '0002_alter_ats_adi_alter_idare_adi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olculmuszedeninxususiyyeti',
            name='sebeb',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Yeni Xüsusiyyət'),
        ),
        migrations.AlterField(
            model_name='zedelenmeninxarakteristikasi',
            name='sebeb',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Yeni xarakteristika'),
        ),
    ]
