version: '3.7'

services:
  dbpr:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: zedelenme
      MYSQL_USER: test
      MYSQL_PASSWORD: your_password
    volumes:
  
      - ../mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - dbpr
    environment:
      PMA_HOST: dbpr
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "8080:80"

  zedelenme:
    image: sadagatasgarov/zedelenme
    container_name: zedelenme
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - dbpr